<?php
/**
 *
 * Et-line icons array.
 * @since 1.0.0
 * @version 1.0.0
 *
 */

if ( ! function_exists( 'et_line_icons' ) ) {
	function et_line_icons() {
		$array = array(
			array( 'icon-adjustments' => 'Adjustments' ),
			array( 'icon-alarmclock' => 'Alarmclock' ),
			array( 'icon-anchor' => 'Anchor' ),
			array( 'icon-aperture' => 'Aperture' ),
			array( 'icon-attachment' => 'Attachment' ),
			array( 'icon-bargraph' => 'Bargraph' ),
			array( 'icon-basket' => 'Basket' ),
			array( 'icon-beaker' => 'Beaker' ),
			array( 'icon-bike' => 'Bike' ),
			array( 'icon-book-open' => 'Book-open' ),
			array( 'icon-briefcase' => 'Briefcase' ),
			array( 'icon-browser' => 'Browser' ),
			array( 'icon-calendar' => 'Calendar' ),
			array( 'icon-camera' => 'Camera' ),
			array( 'icon-caution' => 'Caution' ),
			array( 'icon-chat' => 'Chat' ),
			array( 'icon-circle-compass' => 'Circle-compass' ),
			array( 'icon-clipboard' => 'Clipboard' ),
			array( 'icon-clock' => 'Clock' ),
			array( 'icon-cloud' => 'Cloud' ),
			array( 'icon-compass' => 'Compass' ),
			array( 'icon-desktop' => 'Desktop' ),
			array( 'icon-dial' => 'Dial' ),
			array( 'icon-document' => 'Document' ),
			array( 'icon-documents' => 'Documents' ),
			array( 'icon-download' => 'Download' ),
			array( 'icon-dribbble' => 'Dribbble' ),
			array( 'icon-edit' => 'Edit' ),
			array( 'icon-envelope' => 'Envelope' ),
			array( 'icon-expand' => 'Expand' ),
			array( 'icon-facebook' => 'Facebook' ),
			array( 'icon-flag' => 'Flag' ),
			array( 'icon-focus' => 'Focus' ),
			array( 'icon-gears' => 'Gears' ),
			array( 'icon-genius' => 'Genius' ),
			array( 'icon-gift' => 'Gift' ),
			array( 'icon-global' => 'Global' ),
			array( 'icon-globe' => 'Globe' ),
			array( 'icon-googleplus' => 'Googleplus' ),
			array( 'icon-grid' => 'Grid' ),
			array( 'icon-happy' => 'Happy' ),
			array( 'icon-hazardous' => 'Hazardous' ),
			array( 'icon-heart' => 'Heart' ),
			array( 'icon-hotairballoon' => 'Hotairballoon' ),
			array( 'icon-hourglass' => 'Hourglass' ),
			array( 'icon-key' => 'Key' ),
			array( 'icon-laptop' => 'Laptop' ),
			array( 'icon-layers' => 'Layers' ),
			array( 'icon-lifesaver' => 'Lifesaver' ),
			array( 'icon-lightbulb' => 'Lightbulb' ),
			array( 'icon-linegraph' => 'Linegraph' ),
			array( 'icon-linkedin' => 'Linkedin' ),
			array( 'icon-lock' => 'Lock' ),
			array( 'icon-magnifying-glass' => 'Magnifying-glass' ),
			array( 'icon-map' => 'Map' ),
			array( 'icon-map-pin' => 'Map-pin' ),
			array( 'icon-megaphone' => 'Megaphone' ),
			array( 'icon-mic' => 'Mic' ),
			array( 'icon-mobile' => 'Mobile' ),
			array( 'icon-newspaper' => 'Newspaper' ),
			array( 'icon-notebook' => 'Notebook' ),
			array( 'icon-paintbrush' => 'Paintbrush' ),
			array( 'icon-paperclip' => 'Paperclip' ),
			array( 'icon-pencil' => 'Pencil' ),
			array( 'icon-phone' => 'Phone' ),
			array( 'icon-picture' => 'Picture' ),
			array( 'icon-pictures' => 'Pictures' ),
			array( 'icon-piechart' => 'Piechart' ),
			array( 'icon-presentation' => 'Presentation' ),
			array( 'icon-pricetags' => 'Pricetags' ),
			array( 'icon-printer' => 'Printer' ),
			array( 'icon-profile-female' => 'Profile-female' ),
			array( 'icon-profile-male' => 'Profile-male' ),
			array( 'icon-puzzle' => 'Puzzle' ),
			array( 'icon-quote' => 'Quote' ),
			array( 'icon-recycle' => 'Recycle' ),
			array( 'icon-refresh' => 'Refresh' ),
			array( 'icon-ribbon' => 'Ribbon' ),
			array( 'icon-rss' => 'Rss' ),
			array( 'icon-sad' => 'Sad' ),
			array( 'icon-scissors' => 'Scissors' ),
			array( 'icon-scope' => 'Scope' ),
			array( 'icon-search' => 'Search' ),
			array( 'icon-shield' => 'Shield' ),
			array( 'icon-speedometer' => 'Speedometer' ),
			array( 'icon-strategy' => 'Strategy' ),
			array( 'icon-streetsign' => 'Streetsign' ),
			array( 'icon-tablet' => 'Tablet' ),
			array( 'icon-target' => 'Target' ),
			array( 'icon-telescope' => 'Telescope' ),
			array( 'icon-toolbox' => 'Toolbox' ),
			array( 'icon-tools' => 'Tools' ),
			array( 'icon-tools-2' => 'Tools-2' ),
			array( 'icon-trophy' => 'Trophy' ),
			array( 'icon-tumblr' => 'Tumblr' ),
			array( 'icon-twitter' => 'Twitter' ),
			array( 'icon-upload' => 'Upload' ),
			array( 'icon-video' => 'Video' ),
			array( 'icon-wallet' => 'Wallet' ),
			array( 'icon-wine' => 'Wine' )
		);
		return $array;
	}
}
